### ISSUE TITLE
Clyde doesn't list correct dependencies when installing from AUR

### ISSUE THREAD

**Issue by Daenyth** [Kiwi/clyde#35] opened 2010-04-16 20:28 UTC
```
daenyth@Bragi ~ $ sudo clyde -S gitg
Password: 
:: The following packages should be upgraded first :
    pacman  
:: Do you want to cancel the current operation
::and upgrade these packages now? [Y/n] n

:: gitg package not found, searching for group...
:: gitg group not found, searching AUR...

==> Installing the following packages from repos

Targets (1): gtksourceview2-2.10.0-1  

Total Download Size:    0.00 MB
Total Installed Size:   5.48 MB

==> Installing the following packages from AUR
Targets (1): gitg  

==> Proceed with installation? [Y/n] 
resolving dependencies...
looking for inter-conflicts...
:: Retrieving packages from extra...
gtksourceview2-2.10....  609.9K 1133.5K/s 00:00:01     [#########################################] 100%
checking package integrity...
(6/6) checking for file conflicts                  [#########################################] 100%
(1/6) upgrading glib2                              [#########################################] 100%
(2/6) upgrading atk                                [#########################################] 100%
(3/6) upgrading pango                              [#########################################] 100%
```

It never lists those dependencies.

**Comment by nogweii** [comment] 2010-05-21 00:28
For those who have a slightly hard time reading it (you need to indent ALL the lines 4 spaces for the pre/code block to be used!) installing gitg also install atk/pango, those of which were never listed before hand.

**Comment by Daenyth** [comment] 2010-05-21 01:54
Edited

**Comment by juster** [comment] 2010-09-04 01:48
This should now be fixed by Otto's patch. On second thought this is still imperfect so I will keep the issue open. This will be officially fixed when I finish rewriting stuff.

**Comment by juster** [comment] 2010-11-19 01:32
I can't reproduce the problems from before so I am closing this.

**Closed as completed by juster** 2010-11-19 01:32 UTC
Labels: AUR
