### ISSUE TITLE
Clyde segfaults on all commands

### ISSUE THREAD

**Issue by duckinator** [Kiwi/clyde#118] opened 2011-03-26 19:47 UTC
With: ef671e555b47f2d80075629a005c54f52775e738
I get a segfault, even with just `clyde`.

`clyde` output:
    [~/clyde]$ clyde
    zsh: segmentation fault  clyde

`examples/test` output: https://gist.github.com/888569

`examples/query` output: https://gist.github.com/888570

`examples/aursearch` output: https://gist.github.com/888571

If you need any other info, let me know.

**Comment by juster** [comment] 2011-03-26 20:14
oh those examples should be deleted... I can't seem to reproduce this bug...

**Comment by juster** [comment] 2011-03-26 20:51
do you have any fancy CFLAGS or LDFLAGS exported or special CFLAGS/LDFLAGS in /etc/makepkg.conf?

**Comment by duckinator** [comment] 2011-03-26 21:18
Nothing special exported, haven't touched /etc/makepkg.conf (didn't even know it existed until you mentioned that)

**Comment by vendion** [comment] 2011-03-27 02:53
I am also having this issue, I don't have any special flags exported but I did attempt to install clyde via a hand edited PKGBUILD script because I already have Pacman 3.5.1.

This is the PKGBUILD script i used https://gist.github.com/888866 the changes I made was putting the currently date in the pkgver and also removing the dependency on pacman <3.5

**Comment by duckinator** [comment] 2011-03-27 02:55
I didn't edit anything and it compiled fine. Used PKGBUILD from aur, which seems rather strange. It clones it twice iirc.

**Comment by Ep0chalypse** [comment] 2011-03-27 05:31
Same thing with me...everything in regards to clyde is default....i didnt change anything. Just did a git pull and recompiled...still no luck.

**Comment by xavierd** [comment] 2011-03-27 10:16
In fact, on i686 clyde is working as expected, but on x86_64 clyde always segfault!

**Comment by vendion** [comment] 2011-03-27 11:17
If it helps here is a strace from clyde https://gist.github.com/889129

**Comment by juster** [comment] 2011-03-27 11:26
Thanks Rip-Rip and vendion that actually helps explain everything!

**Comment by juster** [comment] 2011-03-27 13:06
I am guessing that the clyde_umask function in utilcore.c was segfaulting for x86_64 though I'm not sure why. Please try the latest commit 86f9669e474979b4b5335e646ef59bd29c17fda9... aka reinstall clyde-git.

**Comment by juster** [comment] 2011-03-27 13:37
No it still doesn't work... I have got an emulator to test x86_64 though.

**Comment by juster** [comment] 2011-03-27 14:05
Ah I didn't use size_t properly. The latest commit works in my emulator for x86_64.

**Comment by vendion** [comment] 2011-03-27 14:36
Confirmed your latest commit does work on x86_64 machines, thank you

**Comment by juster** [comment] 2011-03-27 14:59
Cool! closing

**Closed as completed by juster** 2011-03-27 14:59 UTC
Labels: Bug
