### ISSUE TITLE
Update overview (old version --> new version)

### ISSUE THREAD

**Issue by mokasin** [Kiwi/clyde#92] opened 2011-01-08 10:38 UTC
When updating it would be nice if clyde would show the old version and the new version of the packages.

Something like:
Package1 [0.1] --> [0.2]
Package2 [0.45] --> [0.5]

**Comment by juster** [comment] 2011-02-16 15:15
This is a duplicate of #23. Closing this issue but I do plan on implementing it.

**Closed as completed by juster** 2011-02-16 15:15 UTC
Labels: Planned
