### ISSUE TITLE
Ronn dependency

### ISSUE THREAD

**Issue by aeosynth** [Kiwi/clyde#75] opened 2010-09-08 13:58 UTC
Hi, I'm trying to install the clyde-git AUR package, but my build fails with `make: ronn: Command not found` .

**Comment by OttoAllmendinger** [comment] 2010-09-08 19:52
See discussion here f7dc25b281c6ad9d576a1d500827a948768d5a7f#Makefile-P6

I think the problem is that git checks out the files and sets the timestamps in a way that the source file is sometimes newer than the target file and Make wants to run ronn even if it isn't necessary 

One possible solution is to execute "touch $target_file", another is to skip making the man page by default

**Comment by aeosynth** [comment] 2010-09-09 00:58
> another is to skip making the man page by default

Like you said in the arch thread, this whole ronn business is for developers, not users; imo the simplest thing would be to add a flag in the pkgbuild which skips making the man page. Developers probably don't use the pkgbuild anyway, instead manually pulling and making.

**Comment by juster** [comment] 2010-09-10 01:17
Thanks aeosynth for reporting the problem. It should be fixed now. An error is displayed if this happens but the make will succeed. For the record I posted on the forum. Otto reported the problem and diagnosed it properly.

**Closed as completed by juster** 2010-09-10 01:17 UTC
